// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfuceucqjgyarlbbkgvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mdWNldWNxamd5YXJsYmJrZ3Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUyMDk2NTIsImV4cCI6MjA4MDc4NTY1Mn0.34QdEvpitjx3rwLmBt6eB0-bPVxuKVcnnU29AyH4N50";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);